name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Run examples
      run: |
        for example in examples/*
        do
          echo $example
          name=$(basename "${example%.rs}")
          echo $name
          mkdir -p "/tmp/example-objects/"
          cargo run --example "$name" -- -o "/tmp/example-objects/$name.o"
        done
